export const FETCH_CONDITIONS = 'FETCH_CONDITIONS';
export const FETCH_SUBSYSTEMS = 'FETCH_SUBSYSTEMS';
export const HIDE_COMPONENT = 'HIDE_COMPONENT';
export const SET_POSITION = 'SET_POSITION';
export const SWITCH_VISIBILITY_FILTER = 'SWITCH_VISIBILITY_FILTER';
