export const FETCH_CONDITIONS = 'FETCH_CONDITIONS';
export const FETCH_VISIBILITY_FILTERS = 'FETCH_VISIBILITY_FILTERS';
export const FETCH_POSITIONS = 'FETCH_POSITIONS';
export const SET_POSITION = 'SET_POSITION';
export const SWITCH_VISIBILITY_FILTER = 'SWITCH_VISIBILITY_FILTER';
